# Generated by Django 3.0.5 on 2021-03-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=400)),
                ('movie_genre', models.TextField()),
                ('movie_studio', models.TextField()),
                ('movie_director', models.TextField()),
                ('Movie_cast', models.TextField()),
                ('box_office_collection', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
